# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(450, 550)
        Form.setMinimumSize(QtCore.QSize(450, 550))
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(40, 40, 370, 480))
        self.widget.setStyleSheet("QPushButton{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0.375 rgba(20, 47, 78 219), stop: 1 rgba(85, 95, 112, 226));\n"
"    color:rgba(255, 255, 255, 210);\n"
"    border-radius:5px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0.375 rgba(40, 67, 98 219), stop: 1 rgba(105, 118, 132, 226));\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"    background-color:rgba(105, 118, 132, 200);\n"
"}")
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(30, 30, 300, 420))
        self.label.setStyleSheet("border-image: url(:/images/back.png);\n"
"border-radius:20px;")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setGeometry(QtCore.QRect(40, 60, 280, 390))
        self.label_3.setStyleSheet("background-color:rgba(0, 0, 0, 100);\n"
"border-radius:15px;")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setGeometry(QtCore.QRect(40, 80, 281, 41))
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color:rgba(255, 255, 255, 210);")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.LoginEdit = QtWidgets.QLineEdit(self.widget)
        self.LoginEdit.setGeometry(QtCore.QRect(80, 150, 200, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.LoginEdit.setFont(font)
        self.LoginEdit.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(105, 118, 132, 255);\n"
"color:rgba(255, 255, 255, 230);\n"
"padding-bottom:7px;\n"
"")
        self.LoginEdit.setObjectName("LoginEdit")
        self.PasswordEdit = QtWidgets.QLineEdit(self.widget)
        self.PasswordEdit.setGeometry(QtCore.QRect(80, 215, 200, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.PasswordEdit.setFont(font)
        self.PasswordEdit.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(105, 118, 132, 255);\n"
"color:rgba(255, 255, 255, 230);\n"
"padding-bottom:7px;\n"
"")
        self.PasswordEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.PasswordEdit.setObjectName("PasswordEdit")
        self.loginBtn = QtWidgets.QPushButton(self.widget)
        self.loginBtn.setGeometry(QtCore.QRect(80, 300, 200, 40))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.loginBtn.setFont(font)
        self.loginBtn.setObjectName("loginBtn")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(30, 30, 300, 420))
        self.label_2.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:0.715909, stop:0.375 rgba(0, 0, 0, 50), stop: 0.835227 rgba(0, 0, 0, 75));\n"
"border-radius:20px;")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.RegisterButton = QtWidgets.QPushButton(self.widget)
        self.RegisterButton.setGeometry(QtCore.QRect(80, 350, 200, 40))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.RegisterButton.setFont(font)
        self.RegisterButton.setStyleSheet("QPushButton#pushButton{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0.375 rgba(20, 47, 78 219), stop: 1 rgba(85, 95, 112, 226));\n"
"    color:rgba(255, 255, 255, 210);\n"
"    border-radius:5px;\n"
"}\n"
"QPushButton#pushButton:hover{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0.375 rgba(40, 67, 98 219), stop: 1 rgba(105, 118, 132, 226));\n"
"}\n"
"QPushButton#pushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"    background-color:rgba(105, 118, 132, 200);\n"
"}")
        self.RegisterButton.setObjectName("RegisterButton")
        self.label_6 = QtWidgets.QLabel(self.widget)
        self.label_6.setGeometry(QtCore.QRect(30, 30, 300, 420))
        self.label_6.setStyleSheet("background-color: rgb(240, 240, 240);\n"
"border-radius:20px;")
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.close_btn = QtWidgets.QPushButton(self.widget)
        self.close_btn.setGeometry(QtCore.QRect(130, 400, 93, 28))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.close_btn.setFont(font)
        self.close_btn.setStyleSheet("background-color:none;\n"
"border:none;\n"
"")
        self.close_btn.setObjectName("close_btn")
        self.checkBox = QtWidgets.QCheckBox(self.widget)
        self.checkBox.setGeometry(QtCore.QRect(80, 260, 201, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.checkBox.setFont(font)
        self.checkBox.setStyleSheet("color:rgb(206, 206, 206);\n"
"background-color:none;")
        self.checkBox.setObjectName("checkBox")
        self.label_6.raise_()
        self.label_2.raise_()
        self.label.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.LoginEdit.raise_()
        self.PasswordEdit.raise_()
        self.loginBtn.raise_()
        self.RegisterButton.raise_()
        self.close_btn.raise_()
        self.checkBox.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_4.setText(_translate("Form", "DEADLINER"))
        self.LoginEdit.setPlaceholderText(_translate("Form", "Имя пользователя"))
        self.PasswordEdit.setPlaceholderText(_translate("Form", "Пароль"))
        self.loginBtn.setText(_translate("Form", "Вход"))
        self.RegisterButton.setText(_translate("Form", "Новый пользователь"))
        self.close_btn.setText(_translate("Form", "закрыть окно"))
        self.checkBox.setText(_translate("Form", "запомнить пароль"))
import res_rc
